
[package]
name = "iptrap"
version = "1.0.1"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "A fast, stateless TCP sinkhole"
license = "ISC"
homepage = "https://github.com/jedisct1/iptrap"
repository = "https://github.com/jedisct1/iptrap"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq.git"

[dependencies.time]
time = "*"

[dependencies.rustc-serialize]
rustc-serialize = "*"

[dependencies.rand]
rustc-rand = "*"

[dependencies.libc]
libc = "*"

[dependencies.log]
log = "*"

[lib]
name = "iptrap"
path = "src/lib.rs"
