
[package]
name = "iptrap"
version = "1.0.2"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "A fast, stateless TCP sinkhole"
license = "ISC"
homepage = "https://github.com/jedisct1/iptrap"
repository = "https://github.com/jedisct1/iptrap"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq.git"

[dependencies.time]
version = "~0.1.35"

[dependencies.rustc-serialize]
version = "~0.3.19"

[dependencies.rand]
version = "~0.3.14"

[dependencies.libc]
version = "~0.2.12"

[dependencies.log]
version = "~0.3.6"

[lib]
name = "iptrap"
path = "src/lib.rs"
