
[package]
name = "iptrap"
version = "0.0.1"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies.zmq]
git = "https://github.com/jedisct1/rust-zmq"

[lib]
name = "iptrap"
path = "src/lib.rs"
